name: Test Upload SDK Version Action

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Target platform (ios, android, flutter, reactnative, unity)"
        required: true
        default: ios
      version:
        description: "SDK version to publish"
        required: true
        default: 6.0.0
      dryRun:
        description: "Dry run (true/false)"
        required: false
        default: "true"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test action from commit
        uses: embrace-io/public-actions/upload-sdk-version@1841c9025e9640e5bbf83db6900b828df30addeb
        with:
          platform: ${{ inputs.platform }}
          version: ${{ inputs.version }}
          dryRun: ${{ inputs.dryRun }}
          uploadUrl: ${{ vars.SDK_VERSION_URL }}
        env:
          SDK_VERSION_TOKEN: ${{ secrets.SDK_VERSION_TOKEN }}
